-- Adiciona 42 produtos novos ao catálogo e recria services_product_check.
--
-- Pedido de 10/10/2026. Grafias normalizadas a partir da lista recebida:
-- 'Cognishift.' -> 'Cognishift', 'curvereset' -> 'Curvereset',
-- 'sharpfocus' -> 'Sharpfocus', 'Effect plus' -> 'Effect Plus',
-- 'Nerver Elief Gelatin' -> 'Nerve Relief Gelatin',
-- 'Your Healt World' -> 'Your Health World'.
--
-- Lembrete (ver 20260826140000): services.product NÃO é text livre. Toda inclusão
-- no catálogo do client exige recriar esta constraint aqui, senão o INSERT do
-- agente morre com 23514 (check_violation).

INSERT INTO public.products (id, name, updated_at)
VALUES
  (gen_random_uuid()::text, 'Balancemax', now()),
  (gen_random_uuid()::text, 'Beautycell', now()),
  (gen_random_uuid()::text, 'Bicarburn', now()),
  (gen_random_uuid()::text, 'Brainignition', now()),
  (gen_random_uuid()::text, 'BuzzBalance', now()),
  (gen_random_uuid()::text, 'Cinna Nerves', now()),
  (gen_random_uuid()::text, 'Cognishift', now()),
  (gen_random_uuid()::text, 'Curvereset', now()),
  (gen_random_uuid()::text, 'Deep Ease', now()),
  (gen_random_uuid()::text, 'Effect Plus', now()),
  (gen_random_uuid()::text, 'Family Health Corner', now()),
  (gen_random_uuid()::text, 'Farulena', now()),
  (gen_random_uuid()::text, 'Firm Flow', now()),
  (gen_random_uuid()::text, 'Flora Harmony', now()),
  (gen_random_uuid()::text, 'FlowerNerves', now()),
  (gen_random_uuid()::text, 'Gluco Quiet', now()),
  (gen_random_uuid()::text, 'Glucopoise', now()),
  (gen_random_uuid()::text, 'Glucoserene', now()),
  (gen_random_uuid()::text, 'Glyco Oliva', now()),
  (gen_random_uuid()::text, 'Hard Peak', now()),
  (gen_random_uuid()::text, 'Honey Protocol', now()),
  (gen_random_uuid()::text, 'Im Mush', now()),
  (gen_random_uuid()::text, 'Joint Relax', now()),
  (gen_random_uuid()::text, 'Lipo Jelly', now()),
  (gen_random_uuid()::text, 'Magnesium Uni5', now()),
  (gen_random_uuid()::text, 'Nerve Relief Gelatin', now()),
  (gen_random_uuid()::text, 'One Click Health', now()),
  (gen_random_uuid()::text, 'Peak Rises', now()),
  (gen_random_uuid()::text, 'Prime Greens', now()),
  (gen_random_uuid()::text, 'Red Horse', now()),
  (gen_random_uuid()::text, 'Rose Memory', now()),
  (gen_random_uuid()::text, 'Sharpfocus', now()),
  (gen_random_uuid()::text, 'Skinfortify', now()),
  (gen_random_uuid()::text, 'Stallion Force', now()),
  (gen_random_uuid()::text, 'Strong Peak', now()),
  (gen_random_uuid()::text, 'Trace Eraser', now()),
  (gen_random_uuid()::text, 'Vapo Mind', now()),
  (gen_random_uuid()::text, 'Velvet Lift', now()),
  (gen_random_uuid()::text, 'Vigor Jelly', now()),
  (gen_random_uuid()::text, 'Virilemax', now()),
  (gen_random_uuid()::text, 'Vitahear', now()),
  (gen_random_uuid()::text, 'Your Health World', now())
ON CONFLICT (name) DO NOTHING;

ALTER TABLE public.services
  DROP CONSTRAINT IF EXISTS services_product_check;

ALTER TABLE public.services
  ADD CONSTRAINT services_product_check
  CHECK (
    product IN (
      'Arialief',
      'Alphacur',
      'Blinzador',
      'Feilaira',
      'Garaherb',
      'Karylief',
      'Kymezol',
      'Jertaris',
      'Laellium',
      'Memyts',
      'Presgera',
      'Biografa',
      'Cetacondor',
      'Cetadusse',
      'Sciatilief',
      'Goldenfrib',
      'Felaromi',
      'Tenurima',
      'Ariovira',
      'CucuDrops',
      'Zalovira',
      'Xelovita',
      'Cerami',
      'NATHUREX',
      'Mahgryn',
      'Levhyn',
      'Ariomyx',
      'Alitoryn',
      'Athentys',
      'Velynivo',
      'Mioralab',
      'Vergolief',
      'Olisteren',
      'Halegryn',
      'Danmyts',
      'Maizkidor',
      'Basmontex',
      'Fraganief',
      'Ceramiri',
      'Shapeon',
      'Nexburn',
      'Memoryon',
      'Korvizol',
      'Erectozyn',
      'Thewellnesswize',
      'VIP.Shipping',
      'VisualEase',
      'NerveEase',
      'Steelpower',
      'Gluco Off',
      'Cognivex',
      'Nad Dermal+',
      'Alpharock',
      'Hair Bloom',
      'Guardon',
      'Joint Mend',
      'Keskara',
      'Lipolegs',
      'LipoShape',
      'Mind Recall',
      'Mind Wake',
      'Prostate Vital',
      'Quiet Nerves',
      'Quiet Rest',
      'RingSilence',
      'FlowStrong',
      'Youth Within',
      'Thermo Ignite',
      'Glyco Barrier',
      'Gluco Mild',
      'Horsefil',
      'Honeyfil',
      'Clear Gaze',
      'PagAmerican',
      'Jellyrock',
      'Blue Horse',
      'Nail Defender',
      'Mind Honey Trick',
      'Nerve Relief Protocol',
      'Lean Leg',
      'Soda Burn',
      'Nerve Stride',
      'Honey Vital',
      'Cardio Honey',
      'Gut Active',
      'Military Honey',
      'Golden Nerves',
      'Balancemax',
      'Beautycell',
      'Bicarburn',
      'Brainignition',
      'BuzzBalance',
      'Cinna Nerves',
      'Cognishift',
      'Curvereset',
      'Deep Ease',
      'Effect Plus',
      'Family Health Corner',
      'Farulena',
      'Firm Flow',
      'Flora Harmony',
      'FlowerNerves',
      'Gluco Quiet',
      'Glucopoise',
      'Glucoserene',
      'Glyco Oliva',
      'Hard Peak',
      'Honey Protocol',
      'Im Mush',
      'Joint Relax',
      'Lipo Jelly',
      'Magnesium Uni5',
      'Nerve Relief Gelatin',
      'One Click Health',
      'Peak Rises',
      'Prime Greens',
      'Red Horse',
      'Rose Memory',
      'Sharpfocus',
      'Skinfortify',
      'Stallion Force',
      'Strong Peak',
      'Trace Eraser',
      'Vapo Mind',
      'Velvet Lift',
      'Vigor Jelly',
      'Virilemax',
      'Vitahear',
      'Your Health World'
    )
  );

